### ISSUE TITLE
bin/build-html.sh on OSX produces code error

### ISSUE THREAD

**Issue by seclorum** [halfnelson/moai-sdk#34]
emscripten: latest, fresh install

[code]

[ 21%] Building CXX object libmoai/zlcore/CMakeFiles/zlcore.dir/Users/j/Documents/moai/moai-dev/src/zl-gfx/zl_gfx_opengl.cpp.o
/Users/j/Documents/moai/moai-dev/src/zl-gfx/zl_gfx_opengl.cpp:1272:47: error: use of undeclared identifier
      'GL_WRITE_ONLY'
                return glMapBuffer ( _remapEnum ( target ), GL_WRITE_ONLY );
                                                            ^
/Users/j/Documents/moai/moai-dev/src/zl-gfx/zl_gfx_opengl.cpp:1283:3: error: use of undeclared identifier
      'glUnmapBuffer'; did you mean 'zglUnmapBuffer'?
                glUnmapBuffer ( _remapEnum ( target ));
                ^~~~~~~~~~~~~
                zglUnmapBuffer
/Users/j/Documents/moai/moai-dev/src/zl-gfx/zl_gfx_opengl.cpp:1277:6: note: 'zglUnmapBuffer' declared here
void zglUnmapBuffer ( u32 target ) {
     ^
/Users/j/Documents/moai/moai-dev/src/zl-gfx/zl_gfx_opengl.cpp:1299:3: error: use of undeclared identifier
      'glBindVertexArray'; did you mean 'zglBindVertexArray'?
                glBindVertexArray ( vertexArrayID );
                ^~~~~~~~~~~~~~~~~
                zglBindVertexArray
/Users/j/Documents/moai/moai-dev/src/zl-gfx/zl_gfx_opengl.cpp:1292:6: note: 'zglBindVertexArray' declared here
void zglBindVertexArray ( u32 vertexArrayID ) {
     ^
/Users/j/Documents/moai/moai-dev/src/zl-gfx/zl_gfx_opengl.cpp:1312:3: error: use of undeclared identifier
      'glGenVertexArrays'
                glGenVertexArrays ( 1, &vertexArrayID );
                ^
/Users/j/Documents/moai/moai-dev/src/zl-gfx/zl_gfx_opengl.cpp:1325:3: error: use of undeclared identifier
      'glDeleteVertexArrays'
                glDeleteVertexArrays ( 1, &vertexArrayID );
                ^
5 errors generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
make[3]: **\* [libmoai/zlcore/CMakeFiles/zlcore.dir/Users/j/Documents/moai/moai-dev/src/zl-gfx/zl_gfx_opengl.cpp.o] Error 1
make[2]: **\* [libmoai/zlcore/CMakeFiles/zlcore.dir/all] Error 2
[/code]

**Comment by halfnelson** [comment]
Should all be happy now
